-- ============================================================================
-- indices.sql — Índices propuestos y evaluados para TP5 (Unidad 3, Semana 5)
-- Base: foodstore_tp3_carga
--
-- Cada bloque documenta: la consulta que motivó la propuesta, el índice
-- (creado o descartado), y el resultado real medido con EXPLAIN ANALYZE
-- (control de ruido: 3 corridas en orden intercalado, ver
-- informe_mediciones.md para el detalle completo).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- CASO 1 — Q5: Ranking de clientes por gasto total (DENSE_RANK)
-- Spec: specs/spec_01_pedido_estado_detalle_join.md
-- ----------------------------------------------------------------------------

-- Candidato A — DESCARTADO
-- Propuesto por Kiro para atacar el filtro "estado <> 'CANCELADO'" en el
-- join pedido-cliente. NO SE CREA EN FIRME: el planificador lo ignoro en
-- las 9 de 9 corridas de control (3 escenarios x 3 rondas intercaladas),
-- manteniendo Parallel Seq Scan on pedido en todos los casos.
--
-- Motivo del descarte: la condicion "estado <> 'CANCELADO'" deja pasar
-- ~75% de las filas de pedido (Rows Removed by Filter confirma esto en
-- el plan real). Con esa selectividad tan baja, un indice parcial termina
-- cubriendo casi toda la tabla, y el optimizador prefiere el Seq Scan
-- paralelo antes que recorrer un B-tree casi tan grande como el heap.
-- Es un caso real de "columna con condicion parcial de baja selectividad",
-- uno de los ejemplos de sobreindexacion que pide descartar la consigna.
--
-- CREATE INDEX idx_pedido_no_cancelado_cliente
--     ON pedido (id_cliente)
--     WHERE estado <> 'CANCELADO';
-- (dejado comentado a proposito: NO se aplica)

-- Intervencion aceptada — SET LOCAL work_mem
-- No es un indice, es un ajuste de memoria de sesion. El plan base
-- mostraba el HashAggregate final derramando a disco (Batches: 5,
-- Disk Usage > 0). Con work_mem = '16MB' para esta sesion, el
-- HashAggregate paso a 1 solo batch, 100% en RAM, en las 3 rondas de
-- control sin excepcion. Mejora de tiempo real de ~15-29% segun la
-- ronda (ver informe_mediciones.md).
--
-- No requiere ningun CREATE INDEX ni cambio de schema. Se aplica por
-- sesion antes de correr el reporte de ranking:
--   SET LOCAL work_mem = '16MB';

-- ----------------------------------------------------------------------------
-- CASO 2 — Q6: Productos con precio superior al promedio de su categoria
-- Spec: specs/spec_02_producto_categoria_precio.md
-- ----------------------------------------------------------------------------

-- ACEPTADO, con salvedad importante documentada abajo
CREATE INDEX idx_producto_categoria_precio_activo
    ON producto (id_categoria, precio_lista DESC)
    WHERE activo = TRUE;

-- Resultado inicial (dentro de BEGIN...ROLLBACK): 271.205 s -> 220.899 s (~19%).
-- Medicion final, sobre el indice ya aplicado en firme y tras VACUUM
-- ANALYZE (ver Parte_A_Indices/plan_q6_despues.txt): 271.205 s -> 158.728 s
-- (~41%). Ver informe_mediciones.md Caso 2 para el detalle completo.
-- El indice SI se usa (Index Only Scan, Heap Fetches: 0) y
-- resuelve el AVG de la subconsulta sin volver al heap.
--
-- SALVEDAD: el indice no resuelve el problema de fondo de esta
-- consulta. La subconsulta correlacionada se ejecuta 50.003 veces (una
-- por producto) -- un patron O(n * filas_categoria) que ningun indice
-- puede eliminar, porque el costo esta en la CANTIDAD de ejecuciones
-- del SubPlan, no en el costo de cada ejecucion individual.
--
-- La solucion real a este problema (ya resuelta en TP4-Parte3) es
-- REESCRIBIR la consulta con una tabla derivada que pre-agrega el
-- promedio una sola vez por categoria (JOIN en vez de subconsulta
-- correlacionada), no crear un indice. Ver TP4_Reportes_Analiticos/
-- Parte3/consulta_b_subconsulta.sql (version V2), que resuelve el
-- mismo resultado en segundos.
--
-- Se acepta el indice igual porque: (a) es complementario, no
-- redundante, con idx_productos_categoria_activo (ese no incluye
-- precio_lista); (b) aporta una mejora real aunque modesta; (c) sirve
-- ademas para acelerar cualquier otra consulta futura que ordene
-- productos activos por precio dentro de una categoria.

-- ----------------------------------------------------------------------------
-- CASO 3 — Q4: Top 3 productos por facturacion dentro de cada categoria
-- Spec: specs/spec_03_pedido_fecha_brin.md
-- ----------------------------------------------------------------------------

-- Candidato BRIN — DESCARTADO TRAS MEDICION
-- CREATE INDEX idx_pedido_fecha_hora_brin_tp5
--     ON pedido USING BRIN (fecha_hora)
--     WITH (pages_per_range = 32);
--
-- La evidencia estadistica se registro antes de probarlo:
--   SELECT correlation FROM pg_stats
--   WHERE tablename = 'pedido' AND attname = 'fecha_hora';
--   -> resultado real: 0.013024098 (practicamente nula)
--
-- Se midio dentro de BEGIN...ROLLBACK (ver medir_brin_q4.sql). El plan
-- mantuvo Seq Scan, no uso el BRIN y termino en 571.123 ms
-- (ver plan_q4_brin.txt). Un BRIN funciona eliminando rangos de paginas cuyo [min,max] no
-- intersecta el filtro. Con correlacion ~0, cada rango de paginas
-- contiene fechas de todo el año mezcladas (el seed genero fecha_hora
-- con random() independiente del orden de insercion por id), asi que
-- no hay casi ningun rango descartable. Crear este indice hubiera sido
-- un gasto de tiempo para confirmar algo que la estadistica ya
-- anticipaba: no aporta mejora y se descarta.

-- Candidato B-tree — DESCARTADO (corregido tras auditoria; ver
-- Parte_A_Indices/medir_q4_rondas.sql y plan_q4_rondas_salida.txt)
-- CREATE INDEX idx_pedido_fecha_hora_btree ON pedido (fecha_hora DESC);
--
-- Historial completo de la decision (no se oculta ningun cambio de
-- conclusion, incluida esta ultima reversion):
-- 1) Primera medicion (corrida unica): parecio empeorar el tiempo
--    (658 ms sin indice -> 921 ms con indice). Se habia descartado.
-- 2) Con 3 rondas intercaladas dentro de BEGIN...ROLLBACK (sin
--    archivar la salida completa en su momento) se reporto una mejora
--    consistente de ~8.9% (371.5 -> 338.5 ms, 3 de 3 rondas a favor) y
--    el indice paso a ACEPTADO Y APLICADO EN FIRME.
-- 3) Auditoria externa (2026-09-23): esos numeros de 371.5/338.5 ms no
--    coincidian ni con plan_q4_antes.txt (378 ms, corrida unica) ni con
--    plan_q4_despues.txt (414 ms, corrida unica), y la salida de las 3
--    rondas nunca habia quedado archivada como evidencia verificable
--    -- solo el resumen en el informe. Sin el archivo de salida no hay
--    forma de confirmar si esos numeros fueron reales.
-- 4) Remedicion con DROP/CREATE del indice real dentro de transacciones,
--    3 rondas intercaladas, EXPLAIN (ANALYZE, BUFFERS), salida completa
--    archivada en plan_q4_rondas_salida.txt:
--      Antes:   767.525 / 704.008 / 628.264 ms -> promedio 699.9 ms
--      Despues: 729.226 / 688.866 / 706.615 ms -> promedio 708.2 ms
--    Direccion INCONSISTENTE: ronda 1 mejora ~5.0%, ronda 2 mejora
--    ~2.2%, ronda 3 EMPEORA ~12.5%. Promedio final: el indice empeora
--    el tiempo en ~1.2%. El plan confirma la causa: con el indice,
--    pedido pasa de Parallel Seq Scan (3 workers) a Bitmap Heap Scan
--    SIN paralelismo -- la perdida de paralelismo compensa o supera la
--    ganancia de evitar el Seq Scan, el mismo riesgo que ya se habia
--    anticipado en spec_03 y que se confirmo en TP3-Q3.
-- 5) Conclusion final: DESCARTADO. El indice fue eliminado de
--    foodstore_tp3_carga (no se mantiene aplicado en firme). Los
--    tiempos absolutos de esta remedicion (~700 ms) tampoco coinciden
--    con los ~370 ms de la medicion anterior; no hay entorno de
--    benchmark controlado (maquina de desarrollo compartida con otros
--    procesos), asi que solo la comparacion relativa DENTRO de cada
--    sesion (antes vs. despues, intercalado) es interpretable, y esa
--    comparacion, hoy, no favorece al indice de forma consistente.

-- Intervencion complementaria — SET LOCAL work_mem (igual que en Caso 1 y en TP4)
--   SET LOCAL work_mem = '16MB';
-- Ya confirmado en TP4-Parte4 que resuelve el spill a disco del
-- HashAggregate de esta misma consulta. Es una intervencion distinta
-- y compatible con el indice de arriba (uno ataca el filtro de fecha,
-- el otro el spill del agregado) -- no se remidio la combinacion de
-- ambas en este TP, queda como posible mejora adicional a futuro.

-- ----------------------------------------------------------------------------
-- CASO 4 — Q5: segundo descarte por sobreindexacion (indice redundante con la PK)
-- Spec: specs/spec_01_pedido_estado_detalle_join.md (nota de correccion)
-- ----------------------------------------------------------------------------

-- Candidato B (de la propuesta original de Kiro en Caso 1) — DESCARTADO
-- CREATE INDEX idx_detalle_pedido_id_pedido ON detalle_pedido (id_pedido);
-- (dejado comentado a proposito: NO se aplica)
--
-- Motivo del descarte: la spec original afirmaba que detalle_pedido no
-- tenia ningun indice sobre id_pedido -- eso era falso. La PK de
-- detalle_pedido es PRIMARY KEY (id_pedido, id_producto), y por ser
-- id_pedido su primera columna, pk_detalle_pedido ya sirve como indice
-- utilizable para busquedas y joins por id_pedido solo. Este candidato
-- es redundante con un indice ya existente, el otro ejemplo de
-- sobreindexacion que menciona la consigna (columna de baja
-- cardinalidad sin condicion parcial, o indice redundante con otro ya
-- existente -- este caso es el segundo).
--
-- Demostrado con EXPLAIN (ANALYZE, BUFFERS) de Q5 dentro de
-- BEGIN...ROLLBACK (ver medir_indice_redundante_q5.sql y
-- plan_q5_indice_redundante.txt): el plan es IDENTICO con y sin el
-- candidato -- en ambos casos el planificador usa Parallel Seq Scan
-- sobre detalle_pedido (615.6 ms con el candidato, 612.3 ms sin el,
-- diferencia dentro del ruido). El optimizador ni siquiera considera
-- usar la PK ni el candidato para este patron de acceso: la consulta
-- necesita la mayoria de las filas de detalle_pedido de todas formas,
-- asi que un Hash Join con Seq Scan es mas barato que cualquier acceso
-- por indice. Crear el candidato solo agregaria costo de mantenimiento
-- en cada INSERT/UPDATE/DELETE de detalle_pedido sin ningun beneficio
-- de lectura medible.