-- ============================================================================
-- indices.sql — Índices propuestos y evaluados para TP5 (Unidad 3, Semana 5)
-- Base: foodstore_tp3_carga
--
-- Cada bloque documenta: la consulta que motivó la propuesta, el índice
-- (creado o descartado), y el resultado real medido con EXPLAIN ANALYZE
-- (control de ruido: 3 corridas en orden intercalado, ver
-- informe_mediciones.md para el detalle completo).
-- ============================================================================

-- ----------------------------------------------------------------------------
-- CASO 1 — Q5: Ranking de clientes por gasto total (DENSE_RANK)
-- Spec: specs/spec_01_pedido_estado_detalle_join.md
-- ----------------------------------------------------------------------------

-- Candidato A — DESCARTADO
-- Propuesto por Kiro para atacar el filtro "estado <> 'CANCELADO'" en el
-- join pedido-cliente. NO SE CREA EN FIRME: el planificador lo ignoro en
-- las 9 de 9 corridas de control (3 escenarios x 3 rondas intercaladas),
-- manteniendo Parallel Seq Scan on pedido en todos los casos.
-- Remedido con salida archivada tras la devolucion (medir_q5_rondas.sql
-- -> plan_q5_rondas_salida.txt): el indice no aparece en ninguno de los
-- planes.
--
-- Motivo del descarte: la condicion "estado <> 'CANCELADO'" deja pasar
-- ~75% de las filas de pedido (Rows Removed by Filter confirma esto en
-- el plan real). Con esa selectividad tan baja, un indice parcial termina
-- cubriendo casi toda la tabla, y el optimizador prefiere el Seq Scan
-- paralelo antes que recorrer un B-tree casi tan grande como el heap.
-- Es un caso real de "columna con condicion parcial de baja selectividad",
-- uno de los ejemplos de sobreindexacion que pide descartar la consigna.
--
-- CREATE INDEX idx_pedido_no_cancelado_cliente
--     ON pedido (id_cliente)
--     WHERE estado <> 'CANCELADO';
-- (dejado comentado a proposito: NO se aplica)

-- Candidato B — DESCARTADO (redundante con la PK)
-- Kiro lo propuso como segundo candidato para el join con detalle_pedido.
-- CREATE INDEX idx_detalle_pedido_id_pedido
--     ON detalle_pedido (id_pedido);
-- (dejado comentado a proposito: NO se aplica)
--
-- Motivo del descarte: es redundante con pk_detalle_pedido, la PK
-- compuesta PRIMARY KEY (id_pedido, id_producto). Un B-tree compuesto
-- sirve para buscar por su primera columna sola, asi que la PK ya cubre
-- id_pedido. Evidencia:
--   - plan_detalle_por_id_pedido.txt: WHERE id_pedido = 100 usa
--     Index Scan using pk_detalle_pedido (2.401 ms), sin el candidato.
--   - plan_q5_indice_redundante.txt (medir_indice_redundante_q5.sql,
--     dentro de BEGIN...ROLLBACK): Q5 con el candidato 615.608 ms, sin
--     el candidato 612.285 ms; en los dos casos el planificador lee
--     detalle_pedido con Parallel Seq Scan y no usa el candidato.
-- Es el ejemplo literal de sobreindexacion de la consigna: un indice
-- redundante con otro ya existente. (spec_01 decia por error que no
-- habia indice sobre id_pedido; quedo corregido con una nota.)

-- Intervencion aceptada — SET LOCAL work_mem
-- No es un indice, es un ajuste de memoria de sesion. El plan base
-- mostraba el HashAggregate final derramando a disco (Batches: 5,
-- Disk Usage > 0). Con work_mem = '16MB' para esta sesion, el
-- HashAggregate paso a 1 solo batch, 100% en RAM, en las 3 rondas de
-- control sin excepcion. Mejora de tiempo real de ~15-29% segun la
-- ronda (ver informe_mediciones.md).
-- Remedicion archivada (plan_q5_rondas_salida.txt): ~26% menos en las
-- rondas 2 y 3 (la ronda 1 del baseline paga el arranque en frio), y
-- Batches: 5 -> 1 en las 3 rondas.
--
-- No requiere ningun CREATE INDEX ni cambio de schema. Se aplica por
-- sesion antes de correr el reporte de ranking:
--   SET LOCAL work_mem = '16MB';

-- ----------------------------------------------------------------------------
-- CASO 2 — Q6: Productos con precio superior al promedio de su categoria
-- Spec: specs/spec_02_producto_categoria_precio.md
-- ----------------------------------------------------------------------------

-- ACEPTADO, con salvedad importante documentada abajo
CREATE INDEX IF NOT EXISTS idx_producto_categoria_precio_activo
    ON producto (id_categoria, precio_lista DESC)
    WHERE activo = TRUE;

-- Resultado inicial (dentro de BEGIN...ROLLBACK, sin salida archivada): 271.205 s -> 220.899 s (~19%).
-- Medicion final, sobre el indice ya aplicado en firme y tras VACUUM
-- ANALYZE (ver Parte_A_Indices/plan_q6_despues.txt): 271.205 s -> 158.728 s
-- (~41%). Ver informe_mediciones.md Caso 2 para el detalle completo.
-- El indice SI se usa (Index Only Scan, Heap Fetches: 0) y
-- resuelve el AVG de la subconsulta sin volver al heap.
--
-- SALVEDAD: el indice no resuelve el problema de fondo de esta
-- consulta. La subconsulta correlacionada se ejecuta 50.003 veces (una
-- por producto) -- un patron O(n * filas_categoria) que ningun indice
-- puede eliminar, porque el costo esta en la CANTIDAD de ejecuciones
-- del SubPlan, no en el costo de cada ejecucion individual.
--
-- La solucion real a este problema (ya resuelta en TP4-Parte3) es
-- REESCRIBIR la consulta con una tabla derivada que pre-agrega el
-- promedio una sola vez por categoria (JOIN en vez de subconsulta
-- correlacionada), no crear un indice. Ver TP4_Reportes_Analiticos/
-- Parte3/consulta_b_subconsulta.sql (version V2), que resuelve el
-- mismo resultado en segundos.
--
-- Se acepta el indice igual porque: (a) es complementario, no
-- redundante, con idx_productos_categoria_activo (ese no incluye
-- precio_lista); (b) aporta una mejora real aunque modesta; (c) sirve
-- ademas para acelerar cualquier otra consulta futura que ordene
-- productos activos por precio dentro de una categoria.

-- ----------------------------------------------------------------------------
-- CASO 3 — Q4: Top 3 productos por facturacion dentro de cada categoria
-- Spec: specs/spec_03_pedido_fecha_brin.md
-- ----------------------------------------------------------------------------

-- Candidato BRIN — DESCARTADO SIN CREAR
-- CREATE INDEX idx_pedido_fecha_hora_brin
--     ON pedido USING BRIN (fecha_hora)
--     WITH (pages_per_range = 32);
--
-- Descartado antes de crearlo, con evidencia estadistica:
--   SELECT correlation FROM pg_stats
--   WHERE tablename = 'pedido' AND attname = 'fecha_hora';
--   -> resultado real: 0.013024098 (practicamente nula)
--
-- Un BRIN funciona eliminando rangos de paginas cuyo [min,max] no
-- intersecta el filtro. Con correlacion ~0, cada rango de paginas
-- contiene fechas de todo el año mezcladas (el seed genero fecha_hora
-- con random() independiente del orden de insercion por id), asi que
-- no hay casi ningun rango descartable. Crear este indice hubiera sido
-- un gasto de tiempo para confirmar algo que la estadistica ya
-- garantiza: no va a servir.

-- Candidato B-tree — DESCARTADO (tras remedir con salida archivada)
-- CREATE INDEX idx_pedido_fecha_hora_btree ON pedido (fecha_hora DESC);
-- (dejado comentado a proposito: NO se aplica. Se elimino de la base con
--  DROP INDEX idx_pedido_fecha_hora_btree; ANALYZE pedido;)
--
-- Historial de la decision (documentado completo, no se oculta ningun
-- cambio de conclusion):
-- 1) Primera medicion (corrida unica): parecio empeorar el tiempo
--    (658 ms sin indice -> 921 ms con indice). Se descarto.
-- 2) Control de ruido con 3 rondas intercaladas: 371.5 ms -> 338.5 ms
--    (~8.9%). Se acepto. Esas 3 rondas NO quedaron archivadas, y la
--    diferencia (33 ms) era menor que la variacion observada en la
--    misma consulta sin ningun cambio (entre 365 y 910 ms).
-- 3) Remedicion con salida archivada (medir_q4_rondas.sql ->
--    plan_q4_rondas_salida.txt), 3 rondas intercaladas con
--    EXPLAIN (ANALYZE, BUFFERS):
--      Sin indice: 767.525 / 704.008 / 628.264 ms -> promedio 699.9 ms
--      Con indice: 729.226 / 688.866 / 706.615 ms -> promedio 708.2 ms
--    Direccion inconsistente (mejora en las rondas 1 y 2, empeora ~12%
--    en la 3) y promedio levemente peor con el indice.
--    El plan explica por que: sin indice, pedido se lee con Parallel
--    Seq Scan repartido en varios procesos (loops=2 o 3); con indice
--    pasa a un Bitmap Heap Scan que corre en un solo proceso (loops=1).
--    Se gana en el filtro de fecha pero se pierde el paralelismo.
-- 4) Conclusion final: DESCARTADO. Una mejora que no supera el ruido
--    no justifica el costo de mantener el indice en cada INSERT/UPDATE
--    sobre pedido.

-- Intervencion complementaria — SET LOCAL work_mem (igual que en Caso 1 y en TP4)
--   SET LOCAL work_mem = '16MB';
-- Ya confirmado en TP4-Parte4 que resuelve el spill a disco del
-- HashAggregate de esta misma consulta. Es una intervencion distinta
-- y no depende de ningun indice: ataca el spill del agregado, no el
-- filtro de fecha. Con el B-tree descartado, queda como la unica
-- intervencion aplicable a Q4.


-- ----------------------------------------------------------------------------
-- CASO 4 — Q2: Productos de una categoria en un rango de precio
-- Spec: specs/spec_06_producto_categoria_precio_sin_activo.md
-- (caso agregado en la correccion posterior a la devolucion de la catedra)
-- ----------------------------------------------------------------------------

-- ACEPTADO Y APLICADO EN FIRME
CREATE INDEX IF NOT EXISTS idx_producto_categoria_precio
    ON producto (id_categoria, precio_lista);

-- Por que no sirven los indices que ya existian sobre producto:
-- idx_productos_categoria_activo e idx_producto_categoria_precio_activo
-- son PARCIALES (WHERE activo = TRUE). Q2 no filtra por activo, asi que
-- el planificador no puede usarlos: dejarian afuera productos inactivos
-- que Q2 si tiene que devolver. Por eso este indice NO es parcial.
--
-- Medicion (medir_q2_rondas.sql -> plan_q2_rondas_salida.txt), 3 rondas
-- intercaladas, con el candidato creado dentro de BEGIN...ROLLBACK:
--   Sin indice: 30.757 / 24.997 / 26.580 ms -> promedio 27.4 ms
--   Con indice: 17.925 / 16.431 / 17.330 ms -> promedio 17.2 ms
-- Mejora de ~37% en las 3 rondas, y los rangos no se superponen
-- (sin indice 25-31 ms, con indice 16-18 ms). El plan pasa de
-- Seq Scan on producto (recorre las 50.003 filas y descarta 38.955) a
-- Bitmap Heap Scan con Bitmap Index Scan sobre este indice (lee solo
-- las 11.048 filas que cumplen el filtro). El Sort por precio_lista se
-- mantiene en los dos planes, porque el Bitmap Heap Scan no devuelve
-- las filas ordenadas.
--
-- Antecedente: en TP3 se probo este mismo indice para Q2 con una sola
-- corrida por lado y no mostro mejora (12.384 ms -> 12.787 ms). Con
-- tiempos tan chicos, una corrida por lado queda dentro del ruido; la
-- medicion de 3 rondas intercaladas de este TP si muestra una mejora
-- consistente.